# include:
#   - project: 'devops/devops-tools'
#     ref: security
#     file: '/templates/.gitlab-ci-template.yml'

variables:
  SAST_EXCLUDED_PATHS: "frontend/src/assets/private/**"
  DOCKER_DRIVER: overlay2
  REGISTRY_URL: "eu.gcr.io"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  PROJECT_NAME: "taxfix-central"
  # CI_REGISTRY_IMAGE: "eu.gcr.io/taxfix-central/gitlab-security"

stages:
  #- build
  - test

before_script:
    - mkdir -p ./creds
    - echo $SERVICEACCOUNT | base64 -d > ./creds/sa.json
    - gcloud auth activate-service-account --key-file=./creds/sa.json --project=$PROJECT_NAME
    - gcloud auth configure-docker
    - |
          echo " Release tag -  $CI_COMMIT_TAG"
          CI_COMMIT_TAG=${CI_COMMIT_TAG/v/} 
          export RELEASE_VERSION=$CI_COMMIT_TAG
          if [ -z "$RELEASE_VERSION" ]
          then
            IMAGE_TAG=sha.${CI_COMMIT_SHA}
          else
            IMAGE_TAG=$RELEASE_VERSION-sha.${CI_COMMIT_SHA}
          fi
    - export IMAGE_TAG=$IMAGE_TAG
    - export REGISTRY_IMAGE=${REGISTRY_URL}/$PROJECT_NAME/${CI_PROJECT_NAME}:$IMAGE_TAG
    - export REGISTRY_IMAGE_LATEST=${REGISTRY_URL}/$PROJECT_NAME/${CI_PROJECT_NAME}:latest 
    # - export DOCKER_IMAGE=traefik


# build:
#   variables:
#     DOCKER_TLS_CERTDIR: ""
#   stage: build
#   image: eu.gcr.io/taxfix-central/devops-tools:latest
#   services:
#     - docker:19.03.5-dind
#   script:
    
#     - | 
#         if [ -z "$BUILD_SCRIPT" ]
#         then
#               echo "\$BUILD_SCRIPT is empty"
#               docker build  -t $REGISTRY_IMAGE --build-arg NPM_TOKEN=$NPM_TOKEN  .
#         else
#               echo "\$BUILD_SCRIPT is NOT empty"
#               bash $BUILD_SCRIPT
#         fi
    


include:
  - template: Container-Scanning.gitlab-ci.yml  
container_scanning:
  image: eu.gcr.io/taxfix-central/gitlab/container-scanning:1
  variables:
    CLAIR_OUTPUT: High
    KLAR_TRACE: "true"
    CLAIR_TRACE: "true"


  # test2
