# include:
#   - project: 'devops/devops-tools'
#     ref: security
#     file: '/templates/.gitlab-ci-template.yml'

variables:
  SAST_EXCLUDED_PATHS: "frontend/src/assets/private/**"
  DOCKER_DRIVER: overlay2
  REGISTRY_URL: "eu.gcr.io"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  PROJECT_NAME: "taxfix-central"
  # CI_REGISTRY_IMAGE: "eu.gcr.io/taxfix-central/gitlab-security"

include:
  - template: Container-Scanning.gitlab-ci.yml

stages:
  - build
  - test

services:
  - docker:19.03.5-dind

build:
  image: docker:stable
  stage: build
  variables:
    IMAGE: eu.gcr.io/taxfix-central/devops-tools:latest
  script:
    - docker info
    - docker build -t $IMAGE .
    

container_scanning:
  stage: test
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/klar:2.4.1
  artifacts:
    paths:
      - gl-container-scanning-report.json
